---
version: '3'

services:
  mysql-test:
    image: mysql:5.7
    restart: always
    hostname: mysql-test
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
    - "33060:3306"
    labels:
      NAME: "mysql-test"
